name: Deploy LMS Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Sync code to EC2
        run: |
          rsync -avz --exclude 'venv/' ./ ubuntu@<EC2_PUBLIC_IP>:/opt/lms/

      - name: SSH commands
        run: |
          ssh ubuntu@<EC2_PUBLIC_IP> << 'EOF'
          cd /opt/lms
          docker-compose down
          docker-compose build
          docker-compose up -d
          EOF
